### ISSUE TITLE
Auth[entic/oriz]ation?

### ISSUE THREAD

**Issue by dfaulken** [umts/umasstransit.rodeo#5]
A few different ways we could go with this, ranging from simple and less secure, to complex and more secure:

1. Password-protect the app at the borders with a few different passwords, each of which would be tied to a different level of authentication:
  + maneuver judges
  + quiz graders
  + circle check scorer(s)
  + master of ceremonies
1. Have users create passwords using Devise, and we manually set boolean attributes pertaining to authorization;
1. Shibboleth / users / groups.

Thoughts? (@sherson, @werebus)

**Comment by werebus** [comment]
So, Shibboleth is a little hard because of alumni, guests etc, but we have some experience with it, and we already know how to do it, and we have a list of spire ids we could pre-load.

A few secret codes will be the easiest to bootstrap on the day of, but we don't get any sort of auditing trail, but maybe that's not a big deal.

Devise does have [devise_invitiable](https://github.com/scambra/devise_invitable), which might help in the "getting everyone an account" step.

**Comment by dfaulken** [comment]
Hmm, so seems like this depends on how much we care about knowing precisely who entered what.
