### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by dfaulken** [umts/umasstransit.rodeo#58]
@sherson mentioned that it might be a good idea to do database backups day-of. Probably every minute is fine.

**Comment by dfaulken** [comment]
@sherson also mentioned that we should prepare for losing network connectivity with AWS. I suggested periodically emailing a CSV to... somewhere?

**Comment by fermion** [comment]
Is this hosted in AWS on RDS? If so you could leverage RDS Snapshots.

**Comment by Anbranin** [comment]
Wat plz explane

**Comment by Anbranin** [comment]
I (looked it up.)[http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_CreateSnapshot.html]
So the worrying part in here is this:

> Creating this DB snapshot on a Single-AZ DB instance results in a brief I/O suspension that can last from a few seconds to a few minutes, depending on the size and class of your DB instance.

Considering the number of people that will be using this app at once and saving data, I'm not sure every minute will be cool with this method. Even a few seconds could make quite a bit of difference.

**Comment by werebus** [comment]
FWIW, you *want* that I/O suspension with any DB-backup scheme, because the alternative is that you back up data that changes between when you start the backup and when you finish it, making the backup internally inconsistent.

However, to answer @fermion's question, we have the following AWS resources available to us:

*  A single EC2 instance with no control over it except a root login

It's probably best to not even think of this app as being "on AWS" since there's nothing about it that's any different than an OIT VMWare virtual machine or last year's DO droplet.

So... it's probably going to be a locally installed copy of Postgres or Maria?

**Comment by werebus** [comment]
Also, I want to re-state. Let's not get too bogged down in this.  The app needs to manage to have a 0.09% (no, not 9%) uptime somehow.
