### ISSUE TITLE
Onboard judging

### ISSUE THREAD

**Issue by dfaulken** [umts/umasstransit.rodeo#6]
The 2014 APTA handbook says that out of a possible 50 points, participants can lose:

+ Failing to use turn signals: 1 point per instance
+ Failing to honk before backing up: 3 points per instance
+ Failing to use flashers while backing up: 3 points per instance
+ Moving bus with door open: 3 points per instance
+ Failure to use seat belt: 5 points
+ Poor posture, use of mirrors, use of hands, or use of feet: 2 points
+ Missed ADA announcement: 10 points per instance
+ Sudden stops, starts, or abrupt turns: 1 point per instance

Is there any of this we don't do / anything additional we do?

**Comment by werebus** [comment]
I'll see if I can track down our score sheet.

The one thing that comes to mind, though, is time-keeping.  The on-board judge typically has the stopwatch and records the time and time penalty.

**Comment by werebus** [comment]
So I pulled one of last year's on-board sheets from the supply closet. Here's what's on it:

---

### Section A.  Time to completion

*  1 point off for every second beyond 7 minutes

### Section B.  Safety habits

*  1 point off for each failure to use proper turn signals
*  3 points off for each failure to sound horn before backing
*  3 points off for each failure to use 4-ways while backing
*  3 points off for each instance of moving the bus with the doors open

### Section C.  Smoothness of Operation

*  10 points off for each failure to announce ADA stops
*  1 point off for each sudden stop
*  1 point off for each sudden start
*  1 point off for each abrupt turn
*  25 points off if <25mph on diminishing clearance

---

Then there's a big "Speeding" checkbox for some reason.  I think because we threaten to take away participants entire birthday (:birthday:) if they drive like yahoos?

**Comment by werebus** [comment]
Also, was your interpretation of the handbook that there was a maximum penalty for all of those safety/smoothness type things?  That's interesting; I don't think it usually comes up, because you'd really have to be trying to loose 50 points on the things you've listed.

A few people pretty regularly lose a-hundred-or-so (or more) points on time penalties, though.

**Comment by dfaulken** [comment]
Thanks for looking that up! I'll start on this tomorrow.
